import Navbar from "@/app/components/Navbar"
import type { Metadata } from "next"
import Footer from "../components/Footer"
import PullToRefreshProvider from "@/components/PullToRefreshProvider"
// Ẩn Chat UI
// import FloatingChatButton from "@/components/FloatingChatButton"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function HomeLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <div className="bg-slate-100 min-h-screen flex justify-center overflow-x-hidden">
      <div className="flex flex-col min-h-screen w-full max-w-[1600px] bg-white shadow-2xl relative">
        <Navbar />
        <main className='flex-grow'>
          {children}
        </main>
        <Footer />
        {/* Ẩn Chat UI */}
        {/* <FloatingChatButton /> */}
        {/* Pull to Refresh */}
        <PullToRefreshProvider />
      </div>
    </div>
  )
}
