import Navbar from "@/app/components/Navbar"
import type { Metadata } from "next"
import Footer from "../components/Footer"
import FloatingChatButton from "@/components/FloatingChatButton"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function HomeLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <div>
      <Navbar />
      <main className='flex-grow'>{children}</main>
      <Footer />
      <FloatingChatButton />
    </div>
  )
}
